
test1_run: test1
	./test1

test1: test1.cc ../bitarray.c  ../bitarray.h


test2_run: test2
	./test2

test2: test2.cc ../bitarray.c  ../bitarray.h

test3_run: test3
	./test3

test3: test3.cc ../bitarray.c  ../bitarray.h
